name: Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'VERSION'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependency
        run: |
          sudo gem i fpm -f
      - name: Build
        run: make